# Generated by Django 4.2.4 on 2023-08-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_skills_work_rename_name_education_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_description', models.CharField(max_length=200)),
                ('long_description', models.CharField(max_length=1000)),
                ('gallery_top', models.ImageField(upload_to='')),
                ('gallery_2', models.ImageField(upload_to='')),
                ('gallery_3', models.ImageField(upload_to='')),
            ],
        ),
    ]
