# Generated by Django 4.2.4 on 2023-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.TextField(max_length=4000)),
                ('bio', models.TextField(max_length=20000)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='long_description',
            field=models.TextField(max_length=2500),
        ),
    ]
